/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzariadiferente;

import Bean.TipoSabor;
import DAO.TipoSaborDAO;
import java.util.List;

/**
 *
 * @author George
 */
public class TelaAtualizarPreco extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtualizarPreco
     */
    public TelaAtualizarPreco() {
        initComponents();
        try{
        TipoSaborDAO dao = new TipoSaborDAO();
        List<TipoSabor> lista = dao.getAll();
        id1Label.setText(String.valueOf(lista.get(0).id));
        tipo1Label.setText(lista.get(0).nome);
        tipo1TextField.setText(String.valueOf(lista.get(0).preco));
        id2Label.setText(String.valueOf(lista.get(1).id));
        tipo2Label.setText(lista.get(1).nome);
        tipo2TextField.setText(String.valueOf(lista.get(1).preco));
        id3Label.setText(String.valueOf(lista.get(2).id));
        tipo3Label.setText(lista.get(2).nome);
        tipo3TextField.setText(String.valueOf(lista.get(2).preco));        
        }catch(Exception ex){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        id1Label = new javax.swing.JLabel();
        tipo1Label = new javax.swing.JLabel();
        tipo1TextField = new javax.swing.JTextField();
        id2Label = new javax.swing.JLabel();
        tipo2Label = new javax.swing.JLabel();
        tipo2TextField = new javax.swing.JTextField();
        id3Label = new javax.swing.JLabel();
        tipo3Label = new javax.swing.JLabel();
        tipo3TextField = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tituloLabel.setText("Atualizacao dos valores");

        id1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id1Label.setText("jLabel1");

        tipo1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tipo1Label.setText("tipo 1");

        tipo1TextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        id2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id2Label.setText("jLabel2");

        tipo2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tipo2Label.setText("tipo 2");

        tipo2TextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        id3Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id3Label.setText("jLabel3");

        tipo3Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tipo3Label.setText("tipo 3");

        tipo3TextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        salvarButton.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id2Label)
                            .addComponent(id1Label)
                            .addComponent(id3Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipo3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipo3TextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipo1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipo2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipo2TextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(salvarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(tituloLabel)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo1Label)
                            .addComponent(tipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo3Label)
                            .addComponent(tipo3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id1Label)
                        .addGap(18, 18, 18)
                        .addComponent(id2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id3Label)))
                .addGap(45, 45, 45)
                .addComponent(salvarButton)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarPreco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id1Label;
    private javax.swing.JLabel id2Label;
    private javax.swing.JLabel id3Label;
    private javax.swing.JButton salvarButton;
    private javax.swing.JLabel tipo1Label;
    private javax.swing.JTextField tipo1TextField;
    private javax.swing.JLabel tipo2Label;
    private javax.swing.JTextField tipo2TextField;
    private javax.swing.JLabel tipo3Label;
    private javax.swing.JTextField tipo3TextField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
