/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzariadiferente;

import Bean.Circulo;
import Bean.Forma;
import Bean.Quadrado;
import Bean.Triangulo;
import javax.swing.JOptionPane;

/**
 *
 * @author George
 */
public class TelaPizza extends javax.swing.JFrame {

    Forma forma = null;
    
    /**
     * Creates new form TelaPizza
     */
    public TelaPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizzaLabel = new javax.swing.JLabel();
        formaLabel = new javax.swing.JLabel();
        formasComboBox = new javax.swing.JComboBox<>();
        tamanhoLabel = new javax.swing.JLabel();
        ladoLabel = new javax.swing.JLabel();
        ladoTextField = new javax.swing.JTextField();
        alfaLabel = new javax.swing.JLabel();
        alfaTextField = new javax.swing.JTextField();
        sabor1Label = new javax.swing.JLabel();
        sabor1ComboBox = new javax.swing.JComboBox<>();
        sabor2Label = new javax.swing.JLabel();
        sabor2ComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        valorLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pizzaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pizzaLabel.setText("Pizza");

        formaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formaLabel.setText("Forma");

        formasComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Circulo", "Quadrado", "Triangulo" }));
        formasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formasComboBoxActionPerformed(evt);
            }
        });

        tamanhoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tamanhoLabel.setText("Tamanho");

        ladoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ladoLabel.setText("Lado/Raio");

        ladoTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ladoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ladoTextFieldFocusLost(evt);
            }
        });
        ladoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoTextFieldActionPerformed(evt);
            }
        });

        alfaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alfaLabel.setText("ou Area");

        alfaTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alfaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alfaTextFieldFocusLost(evt);
            }
        });

        sabor1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sabor1Label.setText("Sabor 1");

        sabor1ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sabor1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sabor2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sabor2Label.setText("Sabor 2");

        sabor2ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sabor2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton.setText("Adicionar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        valorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valorLabel.setText("R$:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(formasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tamanhoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ladoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ladoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(alfaLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(alfaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pizzaLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sabor1Label)
                                    .addComponent(sabor2Label))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sabor1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sabor2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                                        .addComponent(valorLabel)
                                        .addGap(154, 154, 154)
                                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alfaTextField, ladoTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pizzaLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formaLabel)
                    .addComponent(formasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamanhoLabel)
                    .addComponent(ladoLabel)
                    .addComponent(ladoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alfaLabel)
                    .addComponent(alfaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sabor1Label)
                    .addComponent(sabor1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sabor2Label)
                    .addComponent(sabor2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valorLabel)
                        .addComponent(totalLabel)))
                .addGap(0, 115, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {alfaTextField, ladoTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code he
    }//GEN-LAST:event_addButtonActionPerformed

    private void ladoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladoTextFieldActionPerformed

    private void ladoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ladoTextFieldFocusLost
        if (ladoTextField.getText().trim().length() > 0){
            double lado = Double.parseDouble(ladoTextField.getText());
            forma.setMedida(lado);
            alfaTextField.setText(String.valueOf(forma.getArea()));
        }
    }//GEN-LAST:event_ladoTextFieldFocusLost

    private void formasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formasComboBoxActionPerformed
        // TODO add your handling code here:
            switch(formasComboBox.getSelectedIndex()){
                case 0:
                    break;
                case 1:
                   forma = new Circulo();
                   break;
                case 2:
                   forma = new Quadrado();
                   break;
                case 3:
                   forma = new Triangulo();
                   break;
            }
    }//GEN-LAST:event_formasComboBoxActionPerformed

    private void alfaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alfaTextFieldFocusLost
        if (alfaTextField.getText().trim().length() > 0){
            double area = Double.parseDouble(alfaTextField.getText());
            forma.setArea(area);
            ladoTextField.setText(String.valueOf(forma.getMedida()));
        }
    }//GEN-LAST:event_alfaTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel alfaLabel;
    private javax.swing.JTextField alfaTextField;
    private javax.swing.JLabel formaLabel;
    private javax.swing.JComboBox<String> formasComboBox;
    private javax.swing.JLabel ladoLabel;
    private javax.swing.JTextField ladoTextField;
    private javax.swing.JLabel pizzaLabel;
    private javax.swing.JComboBox<String> sabor1ComboBox;
    private javax.swing.JLabel sabor1Label;
    private javax.swing.JComboBox<String> sabor2ComboBox;
    private javax.swing.JLabel sabor2Label;
    private javax.swing.JLabel tamanhoLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
