/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzariadiferente;

import Bean.Circulo;
import Bean.Forma;
import Bean.Pedido;
import Bean.Pizza;
import Bean.Quadrado;
import Bean.Sabor;
import Bean.Triangulo;
import DAO.SaborDAO;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author George
 */
public class TelaPizza extends javax.swing.JFrame {

    NumberFormat formatter = new DecimalFormat("#0.00");  
    Pedido pedido;
    Pizza pizza = new Pizza();
    int qtd = 1;

    /**
     * Creates new form TelaPizza
     */
    public TelaPizza() {
        initComponents();
        preencheCombo();
        sabor2ComboBox.setVisible(false);
        sabor2Label.setVisible(false);
        jButton3.setVisible(false);
    }
    
    public void setPedido(Pedido pedido){
        this.pedido = pedido;
    }
    
    public void preencheCombo(){
        SaborDAO sabordao = new SaborDAO();
        List<Sabor> sabor1 = sabordao.getAll();
        List<Sabor> sabor2 = sabordao.getAll();
        sabor1ComboBox.setModel(new DefaultComboBoxModel(sabor1.toArray()));
        sabor2ComboBox.setModel(new DefaultComboBoxModel(sabor2.toArray()));
        List<Sabor> ls = new ArrayList<Sabor>();
        Sabor s = (Sabor)sabor1ComboBox.getSelectedItem();
        ls.add(s);
        pizza.setSabores(ls);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pizzaLabel = new javax.swing.JLabel();
        formaLabel = new javax.swing.JLabel();
        formasComboBox = new javax.swing.JComboBox<>();
        ladoLabel = new javax.swing.JLabel();
        ladoTextField = new javax.swing.JTextField();
        alfaLabel = new javax.swing.JLabel();
        alfaTextField = new javax.swing.JTextField();
        sabor1Label = new javax.swing.JLabel();
        sabor1ComboBox = new javax.swing.JComboBox<>();
        sabor2Label = new javax.swing.JLabel();
        sabor2ComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        valorLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pizzaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pizzaLabel.setText("Pizza");

        formaLabel.setText("Forma");

        formasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Circulo", "Quadrado", "Triangulo" }));
        formasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formasComboBoxActionPerformed(evt);
            }
        });

        ladoLabel.setText("Lado/Raio");

        ladoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ladoTextFieldFocusLost(evt);
            }
        });
        ladoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoTextFieldActionPerformed(evt);
            }
        });

        alfaLabel.setText("ou Area");

        alfaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alfaTextFieldFocusLost(evt);
            }
        });

        sabor1Label.setText("Sabor 1");

        sabor1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sabor1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabor1ComboBoxActionPerformed(evt);
            }
        });

        sabor2Label.setText("Sabor 2");

        sabor2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sabor2ComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sabor2ComboBoxFocusLost(evt);
            }
        });
        sabor2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabor2ComboBoxActionPerformed(evt);
            }
        });

        addButton.setText("Adicionar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        valorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valorLabel.setText("R$:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ladoLabel)
                            .addComponent(formaLabel)
                            .addComponent(sabor1Label)
                            .addComponent(sabor2Label)
                            .addComponent(valorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ladoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alfaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(alfaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(formasComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sabor1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sabor2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(pizzaLabel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alfaTextField, ladoTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pizzaLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaLabel)
                    .addComponent(formasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ladoLabel)
                            .addComponent(ladoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alfaLabel)
                            .addComponent(alfaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sabor1Label)
                            .addComponent(sabor1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sabor2Label)
                            .addComponent(sabor2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valorLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code he
        TelaPizza tp = new TelaPizza();
        //tp.setPedido(pedido);
        if (formasComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(tp, "Selecione o formato da pizza", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
            TelaPedido Tpedido = new TelaPedido();
            Tpedido.setPedido(pedido);
            pedido.addPizza(pizza);
            dispose();
            Tpedido.setVisible(true);
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void ladoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladoTextFieldActionPerformed

    private void ladoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ladoTextFieldFocusLost
        if (ladoTextField.getText().trim().length() > 0) {
            double medida = Double.parseDouble(ladoTextField.getText());
            pizza.getForma().setMedida(medida);
            double area = pizza.getForma().getArea();
            alfaTextField.setText(String.valueOf(formatter.format(pizza.getForma().getArea())));
            TelaPizza tp = new TelaPizza();
            if (area < 100 || area > 1600) {
                JOptionPane.showMessageDialog(tp, "A área da pizza precisa estar entre 100 e 1600 cm²", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                switch (formasComboBox.getSelectedIndex()) {
                    case 1:
                        if (medida < 7 || medida > 23) {
                            JOptionPane.showMessageDialog(tp, "O raio do circulo precisa ter entre 7 e 23 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                    case 2:
                        if (medida < 10 || medida > 40) {
                            JOptionPane.showMessageDialog(tp, "O lado do quadrado precisa ter entre 10 e 40 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                    case 3:
                        if (medida < 20 || medida > 60) {
                            JOptionPane.showMessageDialog(tp, "O lado do triângulo precisa ter entre 20 e 40 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                }
            }
            calculapreco();
        }
    }//GEN-LAST:event_ladoTextFieldFocusLost

    private void formasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formasComboBoxActionPerformed
        // TODO add your handling code here:
        Forma forma =  null;
        switch (formasComboBox.getSelectedIndex()) {
            case 0:
                ladoTextField.setText("");
                alfaTextField.setText("");
                break;
            case 1:
                ladoTextField.setText("");
                alfaTextField.setText("");
                forma = new Circulo();
                break;
            case 2:
                ladoTextField.setText("");
                alfaTextField.setText("");
                forma = new Quadrado();
                break;
            case 3:
                ladoTextField.setText("");
                alfaTextField.setText("");
                forma = new Triangulo();
                break;
        }
        pizza.setForma(forma);
    }//GEN-LAST:event_formasComboBoxActionPerformed

    private void alfaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alfaTextFieldFocusLost
        if (alfaTextField.getText().trim().length() > 0) {
            double area = Double.parseDouble(alfaTextField.getText());
            pizza.getForma().setArea(area);
            double medida =  pizza.getForma().getMedida();
            ladoTextField.setText(String.valueOf(formatter.format(pizza.getForma().getMedida())));
            TelaPizza tp = new TelaPizza();
            if (area < 100 || area > 1600) {
                JOptionPane.showMessageDialog(tp, "A área da pizza precisa estar entre 100 e 1600 cm²", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                switch (formasComboBox.getSelectedIndex()) {
                    case 1:
                        if (medida < 7 || medida > 23) {
                            JOptionPane.showMessageDialog(tp, "O raio do circulo precisa ter entre 7 e 23 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                    case 2:
                        if (medida < 10 || medida > 40) {
                            JOptionPane.showMessageDialog(tp, "O lado do quadrado precisa ter entre 10 e 40 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                    case 3:
                        if (medida < 20 || medida > 60) {
                            JOptionPane.showMessageDialog(tp, "O lado do triângulo precisa ter entre 20 e 40 cm", "ERRO", JOptionPane.ERROR_MESSAGE);
                            ladoTextField.setText("");
                            alfaTextField.setText("");
                        }
                        break;
                }
            }
            calculapreco();
        }
    }//GEN-LAST:event_alfaTextFieldFocusLost

    private void sabor2ComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sabor2ComboBoxFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_sabor2ComboBoxFocusLost
    
    private void calculapreco () {
        totalLabel.setText(String.valueOf(pizza.getPreco()));
    }
    private void sabor1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabor1ComboBoxActionPerformed
        // TODO add your handling code here:
        List<Sabor> ls = new ArrayList<Sabor>();
        Sabor s = (Sabor)sabor1ComboBox.getSelectedItem();
        ls.add(s);
        if(qtd == 2) {
            Sabor s2 = (Sabor)sabor2ComboBox.getSelectedItem();
            ls.add(s2);
        }
        pizza.setSabores(ls);
        calculapreco();
    }//GEN-LAST:event_sabor1ComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sabor2ComboBox.setVisible(true);
        sabor2Label.setVisible(true);
        jButton3.setVisible(true);
        qtd++;
        List<Sabor> ls = new ArrayList<Sabor>();
        Sabor s = (Sabor)sabor1ComboBox.getSelectedItem();
        ls.add(s);
        if(qtd == 2) {
            Sabor s2 = (Sabor)sabor2ComboBox.getSelectedItem();
            ls.add(s2);
        }
        pizza.setSabores(ls);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sabor2ComboBox.setVisible(false);
        sabor2Label.setVisible(false);
        jButton3.setVisible(false);
        qtd--;
         List<Sabor> ls = new ArrayList<Sabor>();
        Sabor s = (Sabor)sabor1ComboBox.getSelectedItem();
        ls.add(s);
        if(qtd == 2) {
            Sabor s2 = (Sabor)sabor2ComboBox.getSelectedItem();
            ls.add(s2);
        }
        pizza.setSabores(ls);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sabor2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabor2ComboBoxActionPerformed
        // TODO add your handling code here:
        List<Sabor> ls = new ArrayList<Sabor>();
        Sabor s = (Sabor)sabor1ComboBox.getSelectedItem();
        ls.add(s);
        Sabor s2 = (Sabor)sabor2ComboBox.getSelectedItem();
        ls.add(s2);
        
        pizza.setSabores(ls);
        calculapreco();
    }//GEN-LAST:event_sabor2ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel alfaLabel;
    private javax.swing.JTextField alfaTextField;
    private javax.swing.JLabel formaLabel;
    private javax.swing.JComboBox<String> formasComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel ladoLabel;
    private javax.swing.JTextField ladoTextField;
    private javax.swing.JLabel pizzaLabel;
    private javax.swing.JComboBox<String> sabor1ComboBox;
    private javax.swing.JLabel sabor1Label;
    private javax.swing.JComboBox<String> sabor2ComboBox;
    private javax.swing.JLabel sabor2Label;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
